package org.example.stepDefs;
import org.openqa.selenium.Point;
import com.github.javafaker.Faker;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import org.example.pages.P01_register;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;
import org.testng.asserts.SoftAssert;

import java.awt.*;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.concurrent.TimeUnit;

import static java.awt.SystemColor.window;
import static org.example.stepDefs.Hooks.driver;

public class D01_register {
P01_register register = new P01_register();
SoftAssert soft = new SoftAssert();
    Faker fake = new Faker();
        @Given("the user is on the registration page and enters valid registration details")
        public void theUserIsOnTheRegistrationPageAndEntersValidRegistrationDetails() throws InterruptedException {
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        register.joinNowButton.click();
        String fakeUserName = fake.name().username();
        register.firstname.sendKeys(fakeUserName);
        String fakeLastName = fake.name().lastName();
        register.lastName.sendKeys(fakeLastName);
        String fakeEmail = fake.internet().emailAddress();
        register.email.sendKeys(fakeEmail);
        String fakePassword = fake.internet().password();
        register.password.sendKeys(fakePassword);
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.jobLookingFor.sendKeys("QA software engineer");
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);",register.createAnEmployerAccount);
        Thread.sleep(500);
        register.signupButton.click();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.student.click();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);",register.Manager);
        Thread.sleep(1500);
        register.fullTime.click();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);",register.whatJobCategories);
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        Thread.sleep(1500);
        register.itSoftwareDevelopment.click();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.expectedSalary.sendKeys("30000");
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.saveAndContinue.click();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.day.click();
        new Actions(driver).click(register.day).sendKeys("15").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.month.click();
        new Actions(driver).click(register.month).sendKeys("April").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.year.click();
        new Actions(driver).click(register.year).sendKeys("1996").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.male.click();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        new Actions(driver).click(register.nationality).sendKeys("Egypt").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);",register.city);
        new Actions(driver).click(register.city).sendKeys("Cairo").sendKeys(Keys.ENTER).perform();
        Thread.sleep(2000);
        new Actions(driver).click(register.area).sendKeys("Mokattam").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.phoneNumber.sendKeys("01022005897");
        register.saveAndContinue2.click();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        }
    @And("user continue the second part of regesteration")
    public void userContinueTheSecondPartOfRegesteration() throws InterruptedException, AWTException {
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        new Actions(driver).click(register.yearsOfExperiance).sendKeys("Less than 1 Year").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.jobTitle.sendKeys("App Tester");
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        new Actions(driver).click(register.company).sendKeys("HUAWEI").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.jobCategory.click();
        new Actions(driver).click(register.jobCategory).sendKeys("Quality").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.fullTime2.click();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.startingFromStartingMonth.click();
        new Actions(driver).click(register.startingFromStartingMonth).sendKeys("February").sendKeys(Keys.ENTER).perform();
        Thread.sleep(500);
        new Actions(driver).click(register.startingFromStartingYear).sendKeys("2021").sendKeys(Keys.ENTER).perform();
        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        register.iCurrentlyWorkThere.click();
        register.experianceSaveButton.click();
        register.educationLevel.click();
        Thread.sleep(500);
        new Actions(driver).click(register.fieldOfStudy).sendKeys("language & translation").sendKeys(Keys.ENTER).perform();
        Thread.sleep(500);
        new Actions(driver).click(register.universityInstitution).sendKeys("CHI").sendKeys(Keys.TAB).perform();
        Thread.sleep(500);
        new Actions(driver).click(register.whenDidYouGetYourDegree).sendKeys("2018").sendKeys(Keys.TAB).perform();
        Thread.sleep(500);
        new Actions(driver).click(register.grade).sendKeys("A / Excellent / 85 -100%").sendKeys(Keys.TAB).perform();
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);",register.uploadButton);
        Thread.sleep(500);
        new Actions(driver).click(register.languages).sendKeys("English").sendKeys(Keys.TAB).perform();
        Thread.sleep(500);
        new Actions(driver).click(register.proficiency).sendKeys("Advanced").sendKeys(Keys.TAB).perform();
        register.addLanguageButton.click();
        Thread.sleep(500);
        new Actions(driver).click(register.skillsTools).sendKeys("Software Testing").sendKeys(Keys.TAB).perform();
        Thread.sleep(1000);
        new Actions(driver).click(register.skillsTools).sendKeys("software development").sendKeys(Keys.TAB).perform();
        Thread.sleep(500);
        register.uploadButton.click();
        Robot robot=new Robot();
        Thread.sleep(1500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_ENTER);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_TAB);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_UP);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_UP);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_UP);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_UP);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_UP);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_UP);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_UP);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_ENTER);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_DOWN);
        Thread.sleep(500);
        robot.keyPress(KeyEvent.VK_ENTER);
        Thread.sleep(1500);
        register.gettingStarted.click();
    }
}